//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseObjectClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adult
    {
        public int AdultId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public System.DateTime Birthday { get; set; }
        public string PhotoURL { get; set; }
        public string Gender { get; set; }
    }
}
