//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseObjectClass
{
    using System;
    using System.Collections.Generic;

    public partial class Adult:IAdult
    {
        
        /* this code isn't needed yet 12.19.2014
         * {
            this.ContactInfo = new HashSet<ContactInfo>();
            this.ContactPreferences = new HashSet<ContactPreference>();
            this.NurseryFemaleParent = new HashSet<NurseryClients>();
            this.NurseryMaleParent = new HashSet<NurseryClients>();
            this.Children = new HashSet<Children>();
            this.Children1 = new HashSet<Children>();
            this.Memberships = new HashSet<Memberships>();
            this.SpiritualGifts = new HashSet<SpiritualGifts>();
            this.EmergencyContact = new HashSet<EmergencyContacts>();
            this.Staffs = new HashSet<Staff>();
            this.Staffs1 = new HashSet<Staff>();
            this.Incidents = new HashSet<Incidents>();
        }     
        */
        public int AdultId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public DateTime Birthday { get; set; } //Birthday made DateTime, edmx had it as String
        public string PhotoURL { get; set; }
        public string Gender { get; set; }

        public Adult() { }
    }

    
}
        /* These parts were generated by the edmx. Disabled 12.19.2014
        public int VisitorContactTrackingContactTrackingId { get; set; }
        public int VisitorContactTrackingContactTrackingId1 { get; set; }
        public int VisitorContactTrackingContactTrackingId2 { get; set; }
        public int VisitorContactTrackingContactTrackingId3 { get; set; }
    
        public virtual ICollection<ContactInfo> ContactInfo { get; set; }
        public virtual ICollection<ContactPreference> ContactPreferences { get; set; }
        public virtual ICollection<NurseryClients> NurseryFemaleParent { get; set; }
        public virtual ICollection<NurseryClients> NurseryMaleParent { get; set; }
        public virtual ICollection<Children> Children { get; set; }
        public virtual ICollection<Children> Children1 { get; set; }
        public virtual ICollection<Memberships> Memberships { get; set; }
        public virtual ICollection<SpiritualGifts> SpiritualGifts { get; set; }
        public virtual ICollection<EmergencyContacts> EmergencyContacts { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Staff> Staffs1 { get; set; }
        public virtual ICollection<Incidents> Incidents { get; set; }
        public virtual VisitorContactTracking VisitorIdContactTracking { get; set; }
        public virtual VisitorContactTracking EnteredByAdultId { get; set; }
        public virtual VisitorContactTracking ContactedByAdultId { get; set; }
    }
}
        */