//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public Children()
        {
            this.ContactInfoes = new HashSet<ContactInfo>();
            this.ContactPreferences = new HashSet<ContactPreference>();
            this.NurseryClients = new HashSet<NurseryClients>();
            this.Memberships = new HashSet<Memberships>();
            this.SpiritualGifts = new HashSet<SpiritualGifts>();
            this.EmergencyContacts = new HashSet<EmergencyContacts>();
        }
    
        public int ChildId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Birthday { get; set; }
        public string PhotoURL { get; set; }
        public string Gender { get; set; }
        public string MaleParentId { get; set; }
        public string FemaleParentId { get; set; }
    
        public virtual ICollection<ContactInfo> ContactInfoes { get; set; }
        public virtual ICollection<ContactPreference> ContactPreferences { get; set; }
        public virtual ICollection<NurseryClients> NurseryClients { get; set; }
        public virtual Adults Adult { get; set; }
        public virtual Adults Adult1 { get; set; }
        public virtual ICollection<Memberships> Memberships { get; set; }
        public virtual ICollection<SpiritualGifts> SpiritualGifts { get; set; }
        public virtual ICollection<EmergencyContacts> EmergencyContacts { get; set; }
    }
}
