//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactInfoID { get; set; }
        public string ContactID { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber1Type { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber2Type { get; set; }
        public string PhoneNumber3 { get; set; }
        public string PhoneNumber3Type { get; set; }
        public string Email1 { get; set; }
        public string Email1Type { get; set; }
        public string Email2 { get; set; }
        public string Email2Type { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string MailingAddress { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingZip { get; set; }
        public string FacebookName { get; set; }
        public string TwitterHandle { get; set; }
        public string InstagramName { get; set; }
    
        public virtual Children Child { get; set; }
        public virtual Adults Adult { get; set; }
    }
}
