//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPreference
    {
        public int ContactPreferenceId { get; set; }
        public string ContactID { get; set; }
        public string PreferredContactMethod1 { get; set; }
        public string PreferredContactMethod2 { get; set; }
        public string PreferredContactMethod3 { get; set; }
        public string PreferredContactMethod4 { get; set; }
        public string PreferredContactMethod5 { get; set; }
    
        public virtual Adults FK_Adult_Contact_Preference { get; set; }
        public virtual Children FK_Child_Contact_Preference { get; set; }
    }
}
