//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseryClients
    {
        public int NurseryClientId { get; set; }
        public string ChildID { get; set; }
        public string MaleParentAdultID { get; set; }
        public string FemaleParentAdultID { get; set; }
        public string ChildCallID { get; set; }
    
        public virtual Children Child { get; set; }
        public virtual Adults FemaleAdult { get; set; }
        public virtual Adults MaleAdult { get; set; }
    }
}
