//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoulardDBModelContainer : DbContext
    {
        public SoulardDBModelContainer()
            : base("name=SoulardDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NurseryClients> NurseryClients { get; set; }
        public DbSet<Adults> Adults { get; set; }
        public DbSet<ContactInfo> ContactInfoes { get; set; }
        public DbSet<ContactPreference> ContactPreferences { get; set; }
        public DbSet<Children> Children { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<SpiritualGifts> SpiritualGifts1 { get; set; }
        public DbSet<Values> Values { get; set; }
        public DbSet<EmergencyContacts> EmergencyContacts { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Incidents> Incidents { get; set; }
        public DbSet<VisitorContactTracking> VisitorContactTrackings { get; set; }
    }
}
