//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpiritualGifts
    {
        public int SpiritualGiftListingsId { get; set; }
        public string SpiritualGift1 { get; set; }
        public string GiftComment1 { get; set; }
        public string SpiritualGift2 { get; set; }
        public string GiftComment2 { get; set; }
        public string SpiritualGift3 { get; set; }
        public string GiftComment3 { get; set; }
        public string SpiritualGift4 { get; set; }
        public string GiftComment4 { get; set; }
        public string SpiritualGift5 { get; set; }
        public string GiftComment5 { get; set; }
        public string SpiritualGift6 { get; set; }
        public string GiftComment6 { get; set; }
        public string SpiritualGift7 { get; set; }
        public string GiftComment7 { get; set; }
        public string SpiritualGift8 { get; set; }
        public string GiftComment8 { get; set; }
        public string PersonId { get; set; }
    
        public virtual Adults Adult { get; set; }
        public virtual Children Child { get; set; }
    }
}
