//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffId { get; set; }
        public string AdultId { get; set; }
        public string PositionTitle { get; set; }
        public string PositionDuties { get; set; }
        public string SupervisorId { get; set; }
        public string Expertise { get; set; }
        public string AreaInChargeOf { get; set; }
        public string Role { get; set; }
    
        public virtual Adults AdultIDLink { get; set; }
        public virtual Adults AdultStaffSupervisor { get; set; }
    }
}
