//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class Values
    {
        public int Id { get; set; }
        public string AccessLevel { get; set; }
        public string PhoneType { get; set; }
        public string EmailType { get; set; }
        public string Title { get; set; }
        public string Suffix { get; set; }
    }
}
