//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRole1.Content
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorContactTracking
    {
        public VisitorContactTracking()
        {
            this.VisitorIdContactTracking = new HashSet<Adults>();
            this.EnteredByAdultId = new HashSet<Adults>();
            this.ContactedByAdultId = new HashSet<Adults>();
        }
    
        public int ContactTrackingId { get; set; }
        public string VisitorId { get; set; }
        public string EnteredBy { get; set; }
        public string ContactedHow { get; set; }
        public string ContactedWhen { get; set; }
        public string Notes { get; set; }
        public string ContactedBy { get; set; }
    
        public virtual ICollection<Adults> VisitorIdContactTracking { get; set; }
        public virtual ICollection<Adults> EnteredByAdultId { get; set; }
        public virtual ICollection<Adults> ContactedByAdultId { get; set; }
    }
}
